Start training...
dataset train metas: 4753
dataset test metas: 1078
  0%|                                                                                | 0/594 [00:00<?, ?it/s]































































































































































































































































































100%|██████████| 594/594 [09:39<00:00,  1.03it/s, Tr Loss=1.95e+3, Tr Rt=1.94e+3, Tr ph=0.0934, Tr nval=3.75]
Start validation!
Traceback (most recent call last):
  File "C:\Dev\DL_e2e\train_e2e.py", line 442, in <module>
    train(args)
  File "C:\Dev\DL_e2e\train_e2e.py", line 286, in train
    avrg_loss, Rt_loss, ph_loss, nval_loss = validation(model_rt, model_ph, model_nval, val_loader, device, criterion_val, epoch, args)
  File "C:\Users\USER\miniconda3\envs\tpu\lib\site-packages\torch\_tensor.py", line 930, in __iter__
    raise TypeError("iteration over a 0-d tensor")
TypeError: iteration over a 0-d tensor
Validation #1 || Loss: 1556.1204