Start training...
dataset train metas: 4753
dataset test metas: 1078
  0%|                                                                                       | 0/594 [00:00<?, ?it/s]




















































































































































































































































































































100%|████████████████████▉| 593/594 [10:22<00:01,  1.05s/it, Tr Loss=5.08e+3, Tr Rt=5.05e+3, Tr ph=0.307, Tr uph=32]
100%|███████████████████| 594/594 [10:23<00:00,  1.05s/it, Tr Loss=9.66e+3, Tr Rt=9.63e+3, Tr ph=0.335, Tr uph=37.3]
Traceback (most recent call last):
  File "C:\Dev\DL_e2e\train_uph.py", line 460, in <module>
    train(args)
  File "C:\Dev\DL_e2e\train_uph.py", line 297, in train
    avrg_loss, Rt_loss, ph_loss, uph_loss = validation(model_rt, model_ph, model_uph, val_loader, device, criterion_val, epoch, args)
  File "C:\Dev\DL_e2e\train_uph.py", line 348, in validation
    imgs, exts, scs, nvals = imgs.to(device).float(), exts.to(device).float(), scs.to(device).float(), nvals.to(device).float()
UnboundLocalError: local variable 'nvals' referenced before assignment